[env:esp_node_5_lora_master]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Bibliotecas necessárias
lib_deps =
    4-20ma/ModbusMaster @ ^2.0.1
    sandeepmistry/LoRa @ ^0.9.0

; Inclui as pastas com headers locais
build_flags =
    -I../common
    -I.

; Monitor serial com decodificador de exceções
monitor_filters = esp32_exception_decoder