[env:esp_node]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; 🔥 IMPORTANTE: aponta para a pasta common (um nível acima)
build_flags =
    -I../common

lib_deps =
    4-20ma/ModbusMaster @ ^2.0.1
